name: docker

on:
  push:
    branches:
      - main
  release:
    types:
      - published

env:
  REPOSITORY: 'ghcr.io/s6n-labs/docker-runner-images'
  APT_UBUNTU_MIRROR: 'http://jp.ports.ubuntu.com/ubuntu-ports/'

jobs:
  build:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.10
        architecture:
          - ARM64
          - X64
        include:
          - architecture: ARM64
            platforms: linux/arm64/v8
            runner: '["self-hosted", "Linux", "ARM64"]'
            suffix: arm64
          - architecture: X64
            platforms: linux/amd64
            runner: '"ubuntu-22.04"'
            suffix: amd64
    runs-on: ${{ fromJSON(matrix.runner) }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u $ --password-stdin

      - name: Get shorter hash of the commit
        id: shorter_hash
        run: echo "hash=$(echo ${GITHUB_SHA} | cut -c1-7)" >> ${GITHUB_OUTPUT}

      - name: Build (minimal)
        run: |
          docker build  \
            --file './${{ matrix.os }}/Dockerfile' \
            --target 'minimal' \
            --build-arg 'APT_UBUNTU_MIRROR=${{ env.APT_UBUNTU_MIRROR }}' \
            -t ${{ env.REPOSITORY }}:${{ matrix.os }}-minimal-${{ steps.shorter_hash.outputs.hash }}-${{ matrix.suffix }} \
            -t ${{ env.REPOSITORY }}:${{ matrix.os }}-minimal-${{ github.event.release.tag_name || 'latest' }}-${{ matrix.suffix }} \
            -t ${{ env.REPOSITORY }}:${{ matrix.os }}-minimal-${{ matrix.suffix }} \
            .

      - name: Build (standard)
        run: |
          docker build  \
            --file './${{ matrix.os }}/Dockerfile' \
            --target 'standard' \
            --build-arg 'APT_UBUNTU_MIRROR=${{ env.APT_UBUNTU_MIRROR }}' \
            -t ${{ env.REPOSITORY }}:${{ matrix.os }}-standard-${{ steps.shorter_hash.outputs.hash }}-${{ matrix.suffix }} \
            -t ${{ env.REPOSITORY }}:${{ matrix.os }}-standard-${{ github.event.release.tag_name || 'latest' }}-${{ matrix.suffix }} \
            -t ${{ env.REPOSITORY }}:${{ matrix.os }}-standard-${{ matrix.suffix }} \
            .

      - name: Build (dind)
        run: |
          docker build  \
            --file './${{ matrix.os }}/Dockerfile' \
            --target 'dind' \
            --build-arg 'APT_UBUNTU_MIRROR=${{ env.APT_UBUNTU_MIRROR }}' \
            -t ${{ env.REPOSITORY }}:${{ matrix.os }}-dind-${{ steps.shorter_hash.outputs.hash }}-${{ matrix.suffix }} \
            -t ${{ env.REPOSITORY }}:${{ matrix.os }}-dind-${{ github.event.release.tag_name || 'latest' }}-${{ matrix.suffix }} \
            -t ${{ env.REPOSITORY }}:${{ matrix.os }}-dind-${{ matrix.suffix }} \
            .

      - name: Push
        run: |
          for VARIANT in 'minimal' 'standard' 'dind'; do
            docker push "${REPOSITORY}:${{ matrix.os }}-${VARIANT}-${{ steps.shorter_hash.outputs.hash }}-${{ matrix.suffix }}"
            docker push "${REPOSITORY}:${{ matrix.os }}-${VARIANT}-${{ github.event.release.tag_name || 'latest' }}-${{ matrix.suffix }}"
            docker push "${REPOSITORY}:${{ matrix.os }}-${VARIANT}-${{ matrix.suffix }}"
          done
    outputs:
      shorter_hash: '${{ steps.shorter_hash.outputs.hash }}'

  combine:
    needs:
      - build
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.10
        variant:
          - minimal
          - standard
          - dind
    runs-on: ubuntu-22.04
    steps:
      - name: Log in to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u $ --password-stdin

      - name: Determine the prefix of tags
        id: tag_prefix
        run: |
          echo "commitish=${REPOSITORY}:${{ matrix.os }}-${{ matrix.variant }}-${{ needs.build.outputs.shorter_hash }}" >> "${GITHUB_OUTPUT}"
          echo "versioned=${REPOSITORY}:${{ matrix.os }}-${{ matrix.variant }}-${{ github.event.release.tag_name || 'latest' }}" >> "${GITHUB_OUTPUT}"

      - name: Create and push multi-arch image manifests
        run: |
          for TAG in '${{ steps.tag_prefix.outputs.commitish }}' '${{ steps.tag_prefix.outputs.versioned }}'; do
            docker manifest create "${TAG}" --amend "${TAG}-amd64" --amend "${TAG}-arm64"
            docker manifest push "${TAG}"
          done
