name: docker

on:
  push:
    branches:
      - main
  release:
    types:
      - published

env:
  REPOSITORY: 'ghcr.io/s6n-jp/docker-runner-images'
  APT_UBUNTU_MIRROR: 'https://mirror.nishi.network/ubuntu-ports/'

jobs:
  build:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.10
        architecture:
          - X64
          - ARM64
        include:
          - architecture: X64
            platforms: linux/amd64
            suffix: amd64
          - architecture: ARM64
            platforms: linux/arm64
            suffix: arm64
    runs-on: [self-hosted, Linux, '${{ matrix.architecture }}']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u $ --password-stdin

      - name: Get shorter hash of the commit
        id: shorter_hash
        run: echo "hash=$(echo ${GITHUB_SHA} | cut -c1-7)" >> ${GITHUB_OUTPUT}

      - run: ls -al

      - name: Build and push (minimal)
        uses: docker/build-push-action@v4
        with:
          push: true
          context: '.'
          file: './${{ matrix.os }}/minimal/Dockerfile'
          build-args: 'APT_UBUNTU_MIRROR=${{ env.APT_UBUNTU_MIRROR }}'
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ matrix.platforms }}
          tags: |
            ${{ env.REPOSITORY }}:${{ matrix.os }}-minimal-${{ steps.shorter_hash.outputs.hash }}-${{ matrix.suffix }}
            ${{ env.REPOSITORY }}:${{ matrix.os }}-minimal-${{ github.event.release.tag_name || 'latest' }}-${{ matrix.suffix }}
            ${{ env.REPOSITORY }}:${{ matrix.os }}-minimal-${{ matrix.suffix }}

      - name: Build and push (standard)
        uses: docker/build-push-action@v4
        with:
          push: true
          context: '.'
          file: './${{ matrix.os }}/standard/Dockerfile'
          build-args: 'APT_UBUNTU_MIRROR=${{ env.APT_UBUNTU_MIRROR }}'
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ matrix.platforms }}
          tags: |
            ${{ env.REPOSITORY }}:${{ matrix.os }}-standard-${{ steps.shorter_hash.outputs.hash }}-${{ matrix.suffix }}
            ${{ env.REPOSITORY }}:${{ matrix.os }}-standard-${{ github.event.release.tag_name || 'latest' }}-${{ matrix.suffix }}
            ${{ env.REPOSITORY }}:${{ matrix.os }}-standard-${{ matrix.suffix }}

      - name: Build and push (dind)
        uses: docker/build-push-action@v4
        with:
          push: true
          context: '.'
          file: './${{ matrix.os }}/dind/Dockerfile'
          build-args: 'APT_UBUNTU_MIRROR=${{ env.APT_UBUNTU_MIRROR }}'
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ matrix.platforms }}
          tags: |
            ${{ env.REPOSITORY }}:${{ matrix.os }}-dind-${{ steps.shorter_hash.outputs.hash }}-${{ matrix.suffix }}
            ${{ env.REPOSITORY }}:${{ matrix.os }}-dind-${{ github.event.release.tag_name || 'latest' }}-${{ matrix.suffix }}
            ${{ env.REPOSITORY }}:${{ matrix.os }}-dind-${{ matrix.suffix }}
    outputs:
      shorter_hash: '${{ steps.shorter_hash.outputs.hash }}'

  combine:
    needs:
      - build
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.10
        variant:
          - minimal
          - standard
          - dind
    runs-on: ubuntu-22.04
    steps:
      - name: Log in to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u $ --password-stdin

      - name: Determine the prefix of tags
        id: tag_prefix
        run: |
          echo "commitish=${REPOSITORY}:${{ matrix.os }}-${{ matrix.variant }}-${{ needs.build.outputs.shorter_hash }}" >> "${GITHUB_OUTPUT}"
          echo "versioned=${REPOSITORY}:${{ matrix.os }}-${{ matrix.variant }}-${{ github.event.release.tag_name || 'latest' }}" >> "${GITHUB_OUTPUT}"

      - name: Create and push multi-arch image manifests
        run: |
          for TAG in '${{ steps.tag_prefix.outputs.commitish }}' '${{ steps.tag_prefix.outputs.versioned }}'; do
            docker manifest create "${TAG}" --amend "${TAG}-amd64" --amend "${TAG}-arm64"
            docker manifest push "${TAG}"
          done
